matrix:
  include:
    - os: windows
      language: node_js
      node_js:
        - node
      script:
        - cmd.exe /c "xlw.bat apply -v -f xebialabs.yaml"

    - os: linux
      language: node_js
      env:
        - XL_DEPLOY_URL=http://1.2.3.4:55667
      script:
        - ./xlw apply -f xebialabs.yaml