matrix:
  include:
  - os: windows
    language: node_js
    node_js:
    - node
    script:
    - cmd.exe /c "xlw.bat apply -v -f xebialabs.yaml"
  - os: linux
    language: node_js
    script:
    - "./xlw apply -f xebialabs.yaml"
env:
  global:
  - secure: iilkRi73fy5GjeMXkVUzvB1tYaSwO8k1f48g2rOzh1T1RnU7r/1Cq0P4pLYTeaOSykcRZKNlD4pRmhPVc8W516tz6eJEh1RMnjrdC/cKSvJTmpMWG8NTQQjj38f0tVDRDMYUfziBDdho+XnP3tUAvdfsKuG1d2lJWaTAv06YTQ8xW5RKEmQMzYt10bPbkNqHvkeARJjcmDih+1E/vQ9mr7u90uv3gLTxSc2kegRIjnrH1Nt9CuOoHNHbf84y40/Rq+5BJa/B4/bGGgdIB1/N6ocmSmMyi4mbAfHkzfR6AmTmTx2sJPZkYG0jtiAhtIemEFRqfeEcyAz8pvD7dd09XdpXQ96iMYAi7cDAP081iW0/THXtkxYs3nszT+uziMLVJLs75DwyY7304lLtiE+s3WLWO4O7R6YqNkGgSceQFiuhXgyhvC/IpFPpCa46Gi8yM3pbYvtK8gKQwB275DESqh2xlfCzTA+bgsLPy9+qKFrCMob7+KX+7akqbm3a5CMoZMsuu/lB8Gp9v2ywp9rPi3V5XM3HHk3rmQSTBQirUZn+uITk6Uq5gt9ju04/arirEj/e7VPH8ym1eVc3YeimgVJ2EHPU4iu4EjiGNKyFoanuffm3wRI24wyFR3jaEKNiE8AG32HHCXHrmKbu5BZmI7ax/DHlS/UXic/C2phmqbI=
  - secure: G1YOtF+D45rfN+WmXgNcDycQGmCPUomhZfC/qCLHJJVhKMAf0poA5HB4djHogCJbKEqO0uL0NjzK/3yo6noyxNkgHovLHSGPAlLg17S1WKlFpolztM5Cj8duqiEV9ew/RIjHZW1mN5157jkMqesb3pYMMV+1UEk80O/oxiMOgqIt4JVfamybGGPiEOIZ15w4a2BHNOusenpbTzbaBdO2r2WQwk7Z2oHwYBZoyz6bVKqSjm1l9vCpMuzXJmM2N/yTbortyjsbmbEiyvxtAQbl2lxC5Uzfez7df5HFhsprRHKkbmviSWFFGHOLsn2xaJ7i3vqH0xG4GanA/L3QlHci764dhoht8vAw2+fxO8JkPf0c5oayIyIA7u8bCl9IcDnJVaWqLCtaTQYhYSu39MlFoog4YmSad9xmjM9U1Hr7IpFjcquBr9Govt9oXmmNTAdIMDErMay2EjT5SZG1RhB5YCVQVJjawaC7gIatT/gOThp+uHZ/K89ezeoipb7hUPUMfjoQkT842yCCitljqviq8py7SStO1XmWYiwudOXT6Em65PRyHd7XjEl6xYt8gdvQ7Gc8Brq/k5jkO55xuKoBEbJx9ivsMPKXl8lMf0ZT3kqa4mLkqlvUQZIAJ92yE/voemd14gveHQ5JwjUFZWSNVi+wxkK8XKEC4kkUUs2O/3o=