resources:
- repo: self
steps:
- script: |
   xlw.bat apply -f xebialabs.yaml
  displayName: 'CMD Script'
  continueOnError: true
  env:
    XL_VALUE_RELEASE_NAME: $(testSecret)
    XL_VALUE_BUILD_NUMBER: $(Build.BuildId)