resources:
- repo: self
steps:
- bash: |
   export DOCKER_PORT=$(docker port gitops_xl-release_1 5516 | awk -F: '{print $2}')
   ./xlw apply -f xebialabs.yaml --xl-release-url http://localhost:$DOCKER_PORT
  displayName: 'Bash Script'
  continueOnError: true
  env:
    XL_VALUE_RELEASE_NAME: $(testSecret)
    XL_VALUE_BUILD_NUMBER: $(Build.BuildId)